services:
  gravify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gravify
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: poetry run python src/main.py